import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header/header";
import { Footer } from "./components/footer/footer";
import { ThemeProvider } from "@/components/theme-provider";
import { ScrollDownButton } from "@radix-ui/react-select";
import { Provider } from "react-redux";
import { store } from "@/redux/Store";
import { NextAuthStore } from "@/provider/next-auth-store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ScrollDownButton/> */}
        <NextAuthStore>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className="h-screen flex flex-col justify-between">
              <div>
                <Header />
                <main>
                  {children}
                </main>
              </div>
              <Footer />
            </div>
          </ThemeProvider>
        </NextAuthStore>
      </body>
    </html>
  );
}
